project_id = "niocfujcwmbwictdpfsn"

[functions.chat-assistant]
verify_jwt = true

[functions.validate-payment]
verify_jwt = true

[functions.export-csv]
verify_jwt = true

[functions.settlement-webhook]
verify_jwt = false

[functions.get-receipt-pdf]
verify_jwt = false

[functions.openai-realtime-token]
verify_jwt = true